services:
  - type: web
    name: hani-md
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm rebuild sharp
    startCommand: node hani.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: PREFIXE
        value: "."
      - key: NOM_OWNER
        value: "H2025"
      - key: NUMERO_OWNER
        value: "2250150252467"
      - key: MODE
        value: "public"
      - key: STICKER_PACK_NAME
        value: "HANI-MD"
      - key: STICKER_AUTHOR_NAME
        value: "H2025"
